Repository HAECHI-LABS/henesis-cli, pull requests merged in 2019-05, with the labels that each got.

#9 feat: add init hook for wretch
  package.json
  src/hooks/init/wretch.ts
  src/rpc/integration.spec.ts
  src/rpc/integration.ts
  test/commands/hello.test.ts
Labels: good first issue, hook

#10 chore: delete .vscode/ and ignore it
  .gitignore
  .vscode/settings.json
Labels: good first issue

#14 style: apply lint, lint script and husky
  package.json
  src/rpc/index.ts
  src/rpc/integration.spec.ts
  src/rpc/integration.ts
  src/types/Integration.ts
Labels: bug, hook
