Repository HAECHI-LABS/henesis-cli, pull requests merged in 2019-06, with the labels that each got.

#39 Jay/fix typo and add help doc
  README.md
  package.json
  src/commands/login.ts
  templates/contracts/example.sol
  templates/handlers/execution2.ts
  templates20/handlers/ERC20-approval.ts
Labels: documentation

#46 feat: improve error message
  src/commands/integration/delete.ts
  src/commands/integration/describe.ts
  src/errors/index.ts
  src/errors/integration.ts
Labels: error handling

#49 fix: change compiler cache directory name
  src/compiler/compilerSupplier.js
Labels: bug

#50 fix: fix evmVersion bug
  .nycrc
  package.json
  src/commands/integration/deploy.ts
  src/compiler/solc.spec.ts
  src/compiler/solc.ts
Labels: bug
